### ISSUE TITLE
您好，网址打开后不显示live2d模型

### ISSUE THREAD

**Issue by Baozi0312** [Pelom777/DestinyChildLive2D#2]

**Comment by Pelom777** [comment]
网络比较慢罢了，你可以clone到本地

**Comment by Baozi0312** [comment]
大佬我把代码用git给clone到了本地了但是打开html文件显示一片空白呜呜

**Comment by Pelom777** [comment]
应该是CORS，看这个[https://pelom.cn/archives/93/#comment-10](https://pelom.cn/archives/93/#comment-10)

**Comment by Baozi0312** [comment]
谢谢大佬！已经打开了孩子很喜欢!
